Private Events handler
JohnHernCode/Rails-Private-Events pull request #1
Opened 2021-03-05 23:21 UTC by RokoVarano

This site is about creating events as a user, so that other users can sing up for them.

Anonymous users can:
  - Click an event to see it's description and who is going
  - Log in
  - Create a new account

Logged in users can:
  - Create new Events
  - Subscribe to other events by clicking the Attend button

Built with

- Ruby 3.0.0 
- Rails 6
- HTML5
- Bootstrap (CDN)

2021-03-06 05:58 UTC, peterrobert requested changes
### INVALID 🛑 
Hello, @RokoVarano  and @JohnHernCode Great work submitting your project for a review. This shows great effort 👏🏿 . However, for your project to be reviewed, it needs to meet the minimum requirements. Kindly check below ⬇️ 

- [ ] Kindly add linters to your project. This will make your project more professional and also allow you to follow best practices. Kindly add linters to your project and submit your project for another review.

![linter_config](https://user-images.githubusercontent.com/32361963/110197072-04f12100-7e5a-11eb-9b00-c2de537c975c.png)

### if you have any question kindly reach me via slack @peterrobert

### HAPPY CODING 💻

2021-03-07 03:12 UTC, NtwaliHeritier requested changes
### **STATUS: CHANGES REQUESTED🛑🛑🛑🛑**

Hello team,
This is an outstanding and great project. I can tell you put in a lot of effort.
Let's make some small changes and make it more impeccable.

[REQUIRED]: In the events_controller's index action, kindly add two lines for upcoming events and past events. Then use the scope you defined in the event model for each of them.

[REQUIRED]: In the users_controller's show action, add @created_events = current_user.events, to show events created by the logged in user. Also add variable for past and upcoming events to be attended by the current user.

[REQUIRED]: Kindly add unit and integration tests to the project.

That's it my friends.
Implement the required changes and ask for another review👍👌
Happy coding💻💻

2021-03-11 21:09 UTC, mahmoud717 requested changes
### Changes required ♻️ 

**Hello guys**

Great job with the project so far it looks amazing, but there are still some changes to be made:
 
---
### Requested 🔴 

- [x] you should make it that a user can't attend the same event twice.
- [ ] should add more tests, right now your app only has one test. it should have more unit and integration tests.



---

please make these changes and request another code review.

if you have any questions don't hesitate to contact me on slack **MahmoudMohammad**

2021-03-12 17:03 UTC, acushlakoncept requested changes
# Status: Changes Required ♻️

### Hello @JohnHernCode  and @RokoVarano, 

You've done an awesome job so far 👌. But there are still some changes that are necessary for this project to be approved.

- [ ] Don't you think there is no need for the owner of the event to have to click the **Attend** Event button since he/she is the **host** already

- [x] You should remove the attend button from past event as there is no need to attend an event that has already past.

- [ ] The user's show page should display the events the user has created 👍  and events that the user is attending to separated in past and upcoming ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))

- [x] Add how to run tests to your ReadMe file.

- [x] Your specs files looks good with a wide tests coverage, but for some reason when I run `rspec` only one example runs. Kindly fix this.
Hint: I noticed running each spec went well, say `rspec spec/features/users_spec.rb` except `rspec spec/features/events_spec.rb` and removing it to run `rspec` ran all the examples, so you probably have an issue with your `feature/events_spec.rb` file.

- [ ] There should be absolutely NO logic in views. Views are only for displaying information that became available to it from its corresponding controller not generating it.  ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) from Pathwright)
I have gone ahead and made some comments on your codebase see affected files below:

**Don't know where to start or how to?** See  [Rails View Helpers Best Practices](https://medium.com/@acushla4real/rails-view-helpers-best-practices-guide-d7d7b6db3db4) 

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla) or reply to this thread, if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

2021-03-12 17:03 UTC, acushlakoncept commented on README.md
> +- run 'rails db:migrate'
Let's make our Install instruction look a bit professional. Enclose commands with backtick(`). Example in your case (don't include the hash (#))
```
#```
git clone https://github.com/JohnHernCode/private-ev
cd private-ev
bundle install
rails db:migrate
#```
```
Make sure to include `rails db:create` before `rails db:migrate` and `yarn`

2021-03-12 17:03 UTC, acushlakoncept commented on app/views/layouts/application.html.erb
>      <%= yield %>
There should be absolutely NO logic in views.

2021-03-12 17:03 UTC, acushlakoncept commented on app/views/layouts/_navbar.html.erb
> +  <%end%>
There should be absolutely NO logic in views.

2021-03-12 17:03 UTC, acushlakoncept commented on app/views/events/show.html.erb
> +<%end%>
There should be absolutely NO logic in views.

2021-03-12 23:45 UTC, umairarshadbutt requested changes
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @JohnHernCode and @RokoVarano 
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed.

##

Kindly work on the suggested changes 👇.
- [x] there is one test case that is failing, please fix it.
##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

2021-03-13 00:06 UTC, oloomoses approved these changes
## Congratulations, Project Approved. :muscle: :tada: :clap: 
**Great job working on the suggested changes from the previous review.
You have passed all the requirements for this project :muscle: 
Feel free to merge and close this pull request.**

**I wish you the best in your next project and see you at the top :rocket:** 
#### Happy Coding
_Slack: Oloo Moses_

2021-03-13 00:18 UTC, merged